### ISSUE TITLE
** BUILD FAILED ** message leading to "chuck~: could not load due to incorrect architecture" error in Max

### ISSUE THREAD

**Issue by kidneyhouston** [shakfu/chuck-max#1]
Hi Shakeeb,

following our quick interaction on the Cycling74 forum here a more in-depth issue for troubleshooting (i'm not very experienced, it might be me causing it).

I'm compiling the external myself using the Terminal on an M1 Pro Macbook.  I used the following command:

_git clone https://github.com/shakfu/chuck-max.git
cd chuck-max
make universal
make setup_

Running this gives me the following error message:

** BUILD FAILED **

The following build commands failed:
	CodeSign /Users/.../Documents/Max\ 8/Packages/max-sdk/build/chuck-max/chuck-max/externals/chuck~.mxo (in target 'chuck_tilde' from project 'chuck-max')
(1 failure)
make: *** [universal] Error 65
... symlink created

The external is built completely with its folder in my Max8 directory. Max finds it when typing in an empty object but prints the error message "chuck~: could not load due to incorrect architecture".

Thanks for taking a look, if you can!
Lukas

**Comment by shakfu** [comment]
@kidneyhouston 

Hi Lukas,

No worries, if you have an M1 mac and you are compiling on the same machine you don't need to fuss with the make universal stuff. I'm writing to you on an M1 Mac myself so we'll figure out how to get it working for you!

1. Let's start from scratch. If you have built this module before, just delete the folder where you built it. Check the `~/Documents/Max 8/Packages` folder and make sure that there is no nothing there related to this repo (like a dead symlink for example).

2. I'm assuming you have a `Xcode` installed and also the dependencies detailed in the README and that you have installed them via [Homebrew](https://brew.sh): `brew install cmake bison flex`. These are all necessary to build.

3. To compile this repo, find a folder on your machine that is not synced with iCloud and does not have a space in its patch (i.e. not `~/Documents/Max 8/Packages`). While this is not a hard requirement, it helps to prevent errors caused by syncing and also errors due to spaces in paths.  A good choice could be `~/projects` or `/Users/<username>/projects` or `~/src`.  I will use the latter for the purposes of this tutorial. Now in this folder:

```batch
cd ~/src
git clone https://github.com/shakfu/chuck-max.git
cd chuck-max
make
```

This should build without errors

Check the `chuck-max/externals` folder and ensure that there is a `chuck~.mxo` external there.

4. If all goes well with the steps 1-3 then at this stage you will want to 'install' this package into `~/Documents/Max 8/Packages`

You can do this by picking one of the following two methods:

a) Install it via making a symlink of the `chuck-max` folder with the freshly build externals to `~/Documents/Max 8/Packages`:

```bash
make setup
```

Which is equivalent to:

```bash
ln -s ~/src/chuck-max "~/Documents/Max 8/Packages/chuck-max"
```

**OR**

b) Use your Mac Finder to just drag-move the `chuck-max` folder with the built external to `~/Documents/Max 8/Packages`

I hope the above help, please let me know if you have further issues. IIf you do, it helps to just provide as much information as possible about what you've done and what error messages you see.

**Comment by shakfu** [comment]
I'd like to to add one more thing .. You don't need to install the `chuck-max` folder into your Max sdk folder, because the `max-sdk-base` is already included with this repo. You can find it in `~/src/chuck-max/source/max-sdk-base`

In other words installing it **here**: `/Users/lukashaas/Documents/Max\ 8/Packages/max-sdk/build/chuck-max/chuck-max/externals/chuck~.mxo`  **is most likely the source of your problems**.

It should be one of the following:

1. `/Users/lukashaas/Documents/Max\ 8/Packages/chuck-max` where `chuck-max` is a symlink to `~/src/chuck-max` OR
2. `/Users/lukashaas/Documents/Max\ 8/Packages/chuck-max` where `chuck-max` has been moved here from `~/src/chuck-max` via your Mac Finder.

**Comment by kidneyhouston** [comment]
Hi Shakeeb,

first of all: thanks again for taking the time. This is the first time I am compiling an external. You're being very helpful and I'm trying to keep up as good as I can 😄 

I managed to get it to build without an error throughout the process in the Terminal. Unfortunately, I still get the error message in Max (chuck~: could not load due to incorrect architecture). Here's what I did so far for further troubleshooting:

1. Ran the Homebrew line again to check whether requirements 2, 3 and 4 are met ("brew install cmake bison flex"). This returns "... is already installed and up-to-date." for all three.
2. Deleted all previous installations from `.../Max 8/Packages/`
3. Ran the following command: 

```
git clone https://github.com/shakfu/chuck-max.git
cd chuck-max
make
```

I used this version from the Readme as i couldn't run the version you indicated above:
`git clone git@github.com:shakfu/chuck-max.git`
-> This returns the error "fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists."

4. As stated before, this successfully built the folders and external -> I checked the externals folder, the `chuck~.mxo` file is there.

5. I moved the folder from my `/Users/.../` to `/Documents/Max 8/Packages/` via Finder.

Now once I open Max I can type into a new object and it recognises a `chuck~` object. However once I press enter, Max prints the incorrect architecture error.

Thanks also for pointing out my mistake with building the chuck-max folder into the `max-sdk` folder - this is due to me being new to using Terminal and not realising I pointed to this directory. I went into this folder and deleted the `chuck-max` folder as well.

Is there anything else that could be causing my problem? There is one part of your instructions where I'm not sure I understood everything correctly. Under 2.) in your initial comment you write: 

> I'm assuming you have a Xcode installed and also the dependencies detailed in the README and that you have installed them via [Homebrew](https://brew.sh/): brew install cmake bison flex. These are all necessary to build.

Are cmake, bison and flex the dependencies or do I need to find something else? (I don't know what dependencies are in this context).

Two screenshots from Max, maybe this adds clarity:

<img width="412" alt="Screenshot 2024-04-04 at 00 04 40" src="https://github.com/shakfu/chuck-max/assets/157747250/e6c1acc2-39b4-4768-aaf0-1cb5f72d1577">

<img width="495" alt="Screenshot 2024-04-04 at 00 05 11" src="https://github.com/shakfu/chuck-max/assets/157747250/7a3a43f4-afa7-4da9-acd7-f5dd5fdbd42b">

**Comment by shakfu** [comment]
@kidneyhouston 

Hi Lukas,

Incidentally, you were right about the url to clone the chuck-max repo, I changed my earlier post to reflect that. For dependencies, if you have installed `flex`, `bison`, and `cmake` via homebrew  and you have Xcode then you are good to go. 

Let's see if we can figure what the problem is. For this we need to check a few things:

1. Open Xcode and check the version you have, please provide it.

2. Can you please provide the version of Max you are using. 

3. Next we are going to double-check the architecture of your machine. This requires the terminal:

```bash
uname -m
```
you should get the following if you are on an M1 Mac

```bash
arm64
```

4. Now we are going to check the architecture of the built external. This requires the use of the terminal:

If your `chuck-max` folder is in `~/src` then do the following **after** you have built it successfully:

```bash
cd ~/src/chuck-max
lipo -archs externals/chuck\~.mxo/Contents/MacOS/chuck\~
```

The `lipo -arch <binary>` part retrieves the architecture of the chuck external's binary.

You should get 

```bash
arm64
```

if you just built `chuck-max` with `make`. If you built `chuck-max` with `make universal` you should get:


```bash
x86_64 arm64
```

Please let me know what you actually get with all of the above questions as they will provide the biggest clue to why you are getting an 'architecture error'.

Finally, if all else fails, and since you clearly would like to get this to work, I have attached a zipped compiled `chuck-max` package. It's just compiled on my Mac M1 and I tested it and it works. Once you unzip it just put it in your `~/Documents/Max 8/Packages` folder. 

One more thing to do: if you try it to open this package  in Max, a dialogue "External cannot be loaded due to macOS quarantine" will appear and give some options to try to fix it. In general you can accept this, but in this case **don't take this option** since it will only fix the external and there are other compiled  binaries in the package, namely, [chugins](https://github.com/ccrma/chugins) in the `examples` folder which will not be fixed  and you will end up in an unhelpful loop. 

To make this unzipped package work, you will have to fix permissions manually by going to the unzipped `chuck-max` folder and open the terminal and run the `fix_permissions.sh` script in it as follows:

```bash
cd chuck-max
/bin/sh fix_permissions.sh
```

If you look inside the `fix_permissions.sh` script, it has two lines to remove the automatic quarantine on all non-notarized binaries and enable the external and the related chugins in the examples folder to run (you can, of course, type these out if you'd rather not run the script):

```bash
sudo /usr/bin/xattr -r -d com.apple.quarantine externals
sudo /usr/bin/xattr -r -d com.apple.quarantine examples
```

The `sudo` part will make macOS ask for your password (which willl be your Mac user password and not your appleid). If you have any concerns about this step, then feel free to google either of the two lines above and you will be further informed about this method... which unfortunately feels a bit hackish.  

If you'd rather not put in your password in this case, the other alternative, if I can't help you get it to compile and work on your system, is for you just to wait until I make fully code-signed and notarized release, and then you don't have to bother with the above `fix_permissions.sh` script step.

Hope you get it to work one way or the other!

[chuck-max.zip](https://github.com/shakfu/chuck-max/files/14860934/chuck-max.zip)

**Comment by shakfu** [comment]
@kidneyhouston  I have updated the post above after further testing: please retry the zipped package above which is now re-uploaded with working `fix_permissions.sh` script.

**Comment by kidneyhouston** [comment]
Hi Shakeeb,

I'm repeating myself but again, thanks for going through all of this with such patience!

Your troubleshooting led me to find the problem. I was running Max in Rosetta and wasn't aware of that. Now that I unchecked Rosetta the external works without any problems.

This is my first time posting an issue on Github. Since it was not related to your work, should I delete the thread again?

**Comment by shakfu** [comment]
@kidneyhouston 

> Your troubleshooting led me to find the problem. I was running Max in Rosetta and wasn't aware of that. Now that I unchecked Rosetta the external works without any problems.

I suspected something along those lines but I didn't realize that Max actually has a Rosetta option! It's great you finally got it to work yourself and figured it out. 

Happy to help in any case. :smile:

No need to delete this thread, I will just close it.
